### ISSUE TITLE
Attendance Module - Minor UI Changes in 'My Classes' Screen

### ISSUE THREAD

**Issue by ananya-jain1** [shiksha-platform/frontend-modulefederation#135]
### Description

1. Remove Share button from top right corner
2. The arrow for attendance reports to be towards right (something like this >)
3. Maths is shown as 'MATHS'. It should be in a sentence case like other subjects.

#### How to reproduce

Select 'My Classes' from the home page and choose any class

#### Screenshots

![image](https://user-images.githubusercontent.com/96038973/176169506-a64a9dc4-7f85-4901-8aa6-8d44e4b40cdd.png)

![image](https://user-images.githubusercontent.com/96038973/176170302-30ecf9ca-ca0f-411b-afc1-e041dea25697.png)

**Comment by sagarihanda** [comment]
@meenapriyadarsnee - please update after checking
