### ISSUE TITLE
Attendance Module - UI Changes in Student list on Class details page

### ISSUE THREAD

**Issue by ananya-jain1** [shiksha-platform/frontend-modulefederation#139]
### Description

The text "Student List, Total 3" is not according to the figma design. Here is the link to the figma screen - https://www.figma.com/file/oFy6JKC4V0v1t26ZedMLd4/Shiksha-App-(Dev-file)?node-id=772%3A15688. The screen on sandbox needs to be consistent with this.

'Show More' on the previous screen should come only when there are more than 5 students in the list.

#### How to reproduce

Go to class details page. Under student list, click on 'See More'

#### Screenshots

![image](https://user-images.githubusercontent.com/96038973/176173845-a2b90786-a2d1-4671-9cc3-9b9ab0f9091b.png)

**Comment by reddyganesha15** [comment]
@meenapriyadarsnee Please assign to @sagarkoshti1990
