### ISSUE TITLE
Notifications module to be plugged into the attendance module to enable sending attendance-related notifications

### ISSUE THREAD

**Issue by ananya-jain1** [shiksha-platform/frontend-modulefederation#146]
### Description

1. In the first screenshot, it is to be made consistent with the figma design - https://www.figma.com/file/oFy6JKC4V0v1t26ZedMLd4/Shiksha-App-(Dev-file)?node-id=2525%3A60260. The APIs need to be implemented from the notifications module.
2. In the second screenshot, the flow to send notifications to be taken from notifications module. The module filter should be pre-selected as Attendance here.

#### How to reproduce

Go to class details and click on mark attendance. On the attendance page, click on edit and then submit. On the attendance summary page, click on view message and then on send another message.

#### Screenshots

![image](https://user-images.githubusercontent.com/96038973/176180676-d25bc4a0-bb4a-42c4-91a1-11b3bdcbdc79.png)

![image](https://user-images.githubusercontent.com/96038973/176180714-88357f77-be15-4e63-9658-6dfb532e4483.png)

**Comment by RinkleDang** [comment]
- [ ] Create notifications

**Comment by RinkleDang** [comment]
- [ ] Sagar o connect with Paresh

**Comment by RinkleDang** [comment]
- [ ] Paresh to explore this link and get back to Sagar, connect with Sagar

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 there are few spelling errors. I'm assigning them to @reddyganesha15 

And the recipient list is unavailable, please include that @sagarkoshti1990 


![Image](https://user-images.githubusercontent.com/108782375/182797768-1ad7c364-2f28-4e62-9430-76e3f39960f1.png)



Will close the bug post that



![Image](https://user-images.githubusercontent.com/108782375/182796752-59e5d6f2-9450-4daf-bc41-e391897f9bde.png)

- [ ] Change`` to -> "Add new notification"



![Image](https://user-images.githubusercontent.com/108782375/182796926-d26fe77d-ce08-403d-a32e-564678cbe719.png)

- [ ] Please remove the underscores and replace it with a space



![Image](https://user-images.githubusercontent.com/108782375/182797172-7f524e0b-1033-4fdf-a7c9-7e64a30ad503.png)

- [ ] Change the sentence highlighted to sentence case



![Image](https://user-images.githubusercontent.com/108782375/182797354-66da2e97-69bd-4fd0-b607-28f8637996c0.png)

- [ ] Change to -> View recipients list



![Image](https://user-images.githubusercontent.com/108782375/182797944-5c777373-ffcf-4b34-823d-1e72a75faece.png)

- [ ] Change to -> USE ANOTHER TEMPLATE



![Image](https://user-images.githubusercontent.com/108782375/182798141-08056749-41b7-4625-a805-fff6b01c3562.png)

- [ ] Change to -> REVIEW & SEND NOW




![Image](https://user-images.githubusercontent.com/108782375/182798413-5923120c-5008-4f60-84af-f099c47e87ee.png)
Change to -> View Notification



![Image](https://user-images.githubusercontent.com/108782375/182798599-6e7667c0-30c0-44c6-ae2b-e595dfd54b7b.png)

- [ ] Show highlighted text in sentence case

**Comment by RinkleDang** [comment]
@meenapriyadarsnee please test send other notification
