### ISSUE TITLE
Self Attendance - Conditions to mark attendance

### ISSUE THREAD

**Issue by ananya-jain1** [shiksha-platform/frontend-modulefederation#150]
### Description

1. Attendance got marked even if I didn't submit attendance.
2. The conditions to mark attendance also need to be config driven (submitting selfie & marking location)
3. 'Back to home' button is not working. It should redirect the user to the home page.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots

![image](https://user-images.githubusercontent.com/96038973/176444564-42b515e2-2315-4784-877e-90e2fb7655c8.png)

**Comment by RinkleDang** [comment]
- [ ] Paresh's PR to be merged

**Comment by sagarihanda** [comment]
@meenapriyadarsnee and @RinkleDang - please check if this is still a concern.

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 attendance not getting marked because of the camera issue. After taking a selfie to record attendance, the page displays 'loading' and the attendance doesn't get marked

**Comment by sagarkoshti1990** [comment]
![Image](https://user-images.githubusercontent.com/19996753/179195134-b51788e1-bc26-4bb6-8772-292e87870c37.png)

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 the attendance is still not being marked.
