### ISSUE TITLE
Self Attendance - Bugs on Profile screen

### ISSUE THREAD

**Issue by ananya-jain1** [shiksha-platform/frontend-modulefederation#152]
### Description

1. 'Undefined' is showing everywhere
2. Camera and share button on the top right corner not working (**remove**)
3. Attendance data not showing up
4. No details entered for the user
5. Coming soon to be shown in front of career, class result, awards & competency (**or remove section**)

#### How to reproduce

Go to home screen, click on user profile, click on 'Go to Profile'

#### Screenshots

![image](https://user-images.githubusercontent.com/96038973/176445309-f982f744-94ed-480b-a389-7cf53164fc22.png)
![image](https://user-images.githubusercontent.com/96038973/176445375-c72b612e-1208-4896-832f-75a7bf4cc6f1.png)

**Comment by RinkleDang** [comment]
- [ ] Paresh to see blocker

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 point 2 be rectified. 

please enter any dummy phone number (1234567899)
![image](https://user-images.githubusercontent.com/108782375/178903969-b7b32eb4-9223-4f21-97a0-6d7388f2cfdc.png)


Please change Date of Birth to Indian format (dd/mm/yyyy)
![image](https://user-images.githubusercontent.com/108782375/178904039-55b9a68c-98f3-492e-aa6d-7c9c8665947a.png)
