### ISSUE TITLE
Search Bar being able to handle different type of search 

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#163]
The search bar only allows to search based on Titles of the modules. So, please enter a description in the search bar (in a faded color) that mentions 'enter title hint'
![image](https://user-images.githubusercontent.com/108782375/177540212-f0df5281-c967-498a-b83f-7b89002f5e7d.png)

**Comment by sagarihanda** [comment]
@meenapriyadarsnee enter title hint in the search box.
