### ISSUE TITLE
Voice Search not enabled

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#164]
The voice search option is not working. Remove the voice search icon
![image](https://user-images.githubusercontent.com/108782375/177623639-00866b95-c7c4-4c52-9f09-39f49626749e.png)

**Comment by meenapriyadarsnee** [comment]
@reddyganesha15 button still not removed



![Image](https://user-images.githubusercontent.com/108782375/179448724-251b7fa4-9187-42fb-a604-bf20aa1782c8.png)

**Comment by reddyganesha15** [comment]
Voice button remove from worksheet module please check
