### ISSUE TITLE
Share/ downlaod option not working in detailed worksheet view

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#173]
The share option is not working in the detailed view of the worksheet. Please remove the 'Share' and 'Download' icon or enable it
![image](https://user-images.githubusercontent.com/108782375/177627534-b1437ed7-465c-4f42-8a87-e33f95b67054.png)

**Comment by reddyganesha15** [comment]
share button enabled
