### ISSUE TITLE
My Profile | Editable Fields, Additional Fields

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#181]
### Description

The editable fields under My Profile are Contact Details (email id/ phone number)
Additional Fields to be included can be referred from Figma Dev File
https://www.figma.com/file/oFy6JKC4V0v1t26ZedMLd4/Shiksha-App-(Dev-file)?node-id=5638%3A146273

**Comment by sagarihanda** [comment]
@meenapriyadarsnee - module not yet built.
