### ISSUE TITLE
See More under Attendance Reports of Self Attendance

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#183]
### Description

- [ ] Please remove the 'See More' button 
- [ ] Change title from 'My Monthly Attendance' to 'My Attendance Trends over 3 months'

![image](https://user-images.githubusercontent.com/108782375/178437273-d2220f1b-33d5-4991-8efe-11918f7e58d5.png)

**Comment by sagarihanda** [comment]
Let's do the following:

- [ ] Change title from 'My Monthly Attendance' to 'My Attendance Trends over 3 months'

- [ ] Remove 'See More' button

@RinkleDang @meenapriyadarsnee

**Comment by meenapriyadarsnee** [comment]
@reddyganesha15 please remove the see more button and change the title from 'My Monthly Attendance' to 'My Attendance Trends over 3 months'
