### ISSUE TITLE
Close option in Attendance Summary Report is not working. Remove Close button

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#186]
### Description

The close option in Attendance Summary Report is not working. Please remove the Close button
![image](https://user-images.githubusercontent.com/108782375/178440763-ec8f4867-f3b4-4a7d-9d2b-dbddc087ca67.png)
https://sandbox.shikshaplatform.io/attendance/9eae88b7-1f2d-4561-a64f-871cf7a6b3f2

**Comment by sagarihanda** [comment]
@meenapriyadarsnee - we can remove 'Close' button at the bottom if the top right icon works.

**Comment by meenapriyadarsnee** [comment]
The icon (x) to close document is missing. Please add the same in the place where I have pointed the cursor



![Image](https://user-images.githubusercontent.com/108782375/179450468-d13a2067-4b0d-4dae-acc1-a1f835280a2a.png)
