### ISSUE TITLE
Alignment issues in Questions

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#193]
### Description

The questions are not properly aligned and have a distorted view. Kindly correct them
![image](https://user-images.githubusercontent.com/108782375/178479995-3faf9034-bfc8-4834-a1c2-98a80fe2a80e.png)

**Comment by sagarihanda** [comment]
@meenapriyadarsnee please check with Sagar if this can be controlled at our end? Or is set in DIKSHA only.
