### ISSUE TITLE
Date Configs not working in Daily Attendance Report

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#197]
### Description

The attendance data displayed in the sandbox is available beyond the date selected in the admin config for the Day View of Attendance Reports

Config title: Please select date till which previous attendance may be visible on the app

#### Screenshots

![Screenshot (177)](https://user-images.githubusercontent.com/108782375/178542632-351b1efa-a73c-4b8c-b6d5-798a5b25c180.png)
![Screenshot (178)](https://user-images.githubusercontent.com/108782375/178542660-77f94a35-2492-496a-96b7-2cc1f13ccb22.png)

**Comment by sagarihanda** [comment]
This config is for the view where teachers mark student attendance. So, this should be fine.
