### ISSUE TITLE
Change to sentence case, other grammatical errors

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#201]
### Description

Please enter the following content in sentence case

#### Screenshots

![Screenshot (172)](https://user-images.githubusercontent.com/108782375/178660953-45c4a94b-8edc-4043-9ab2-225846d6ee17.png)
![Screenshot (175)](https://user-images.githubusercontent.com/108782375/178660964-c568a961-6c74-4879-9421-5659c6215411.png)
![image](https://user-images.githubusercontent.com/108782375/178661595-cbecde9b-be0d-4b97-82e5-6f0ee1d8b02f.png)
![image](https://user-images.githubusercontent.com/108782375/178661813-d479b6a9-5abb-4d5c-adb3-a55c81b8088b.png)
![image](https://user-images.githubusercontent.com/108782375/178661847-1519137e-13c9-43e6-aa1f-0743a2b82102.png)
![image](https://user-images.githubusercontent.com/108782375/178662626-76c82086-9cac-4f3c-8775-b699a1512d60.png)

The following should be changed to "View all classes in your school"
![image](https://user-images.githubusercontent.com/108782375/178662974-10af7b32-e0d8-4582-8a37-be7281f007df.png)

**Comment by meenapriyadarsnee** [comment]
@reddyganesha15 these items are yet to be changed



![Image](https://user-images.githubusercontent.com/108782375/179449027-36b0f6a4-9982-423e-a9ee-fb4e0ffaab65.png)


![Image](https://user-images.githubusercontent.com/108782375/179449269-2b279cc2-e297-4216-9b40-b1377b64267c.png)



![Image](https://user-images.githubusercontent.com/108782375/179449316-56ed7582-7227-498c-bfa5-52d18edda3d7.png)

Remove 'Add'


![Image](https://user-images.githubusercontent.com/108782375/179449456-e26714d4-67d1-4256-b40c-043c463cb3a7.png)

**Comment by meenapriyadarsnee** [comment]
The last screenshot needs to be rectified @reddyganesha15

**Comment by RinkleDang** [comment]
@meenapriyadarsnee please retest

**Comment by meenapriyadarsnee** [comment]
These items are yet to be changed. The changes are same as mentioned in the previous comments

- [ ] Item 1
![Image](https://user-images.githubusercontent.com/108782375/182804166-e9dd8bd9-0d16-48c2-846f-51744596e69d.png)

- [ ] Item 2
![Image](https://user-images.githubusercontent.com/108782375/182804678-223d4305-e9ac-4969-bc91-016942ff3b07.png)

- [ ] Item 3
![Image](https://user-images.githubusercontent.com/108782375/182804902-f29afe7d-eed8-471c-aa4a-aecac7f96ee1.png)

- [ ] Item 4
![Image](https://user-images.githubusercontent.com/108782375/182805149-100279e3-25f2-411e-9a63-36851b89671a.png)
