### ISSUE TITLE
Incorrect generation of result in Attendance Summary 

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#202]
### Description

The attendance summary reflects incorrect information contradictory to the attendance marked.

### Screenshots
![Screenshot (195)](https://user-images.githubusercontent.com/108782375/178665146-92c803df-d079-4bb1-ad99-c4e8fc41aaa7.png)
![Screenshot (196)](https://user-images.githubusercontent.com/108782375/178665154-2f50f6d7-1afe-47ea-b200-bdbb71fed748.png)

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 it's not working yet

**Comment by reets2997** [comment]
@meenapriyadarsnee Please check now, closed from Sagar's end
