### ISSUE TITLE
Topic to be multiselect

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#210]
### Description

From Demo

**Comment by sagarkoshti1990** [comment]
as of now worksheet have single select @meenapriyadarsnee

![Image](https://user-images.githubusercontent.com/19996753/180136500-2575fc23-b6c5-4fef-abf8-bcd213843141.png)

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 you can enable multiselect in the Topics. Discussed with team

**Comment by meenapriyadarsnee** [comment]
@sagarkoshti1990 the topics aren't multiselect and I am unable to select any topic. please resolve


![Image](https://user-images.githubusercontent.com/108782375/182808160-425e008e-6d85-4009-a48d-9c3107270dff.png)
