### ISSUE TITLE
Include answers for subjective questions: Check if subjective answers are available in Diksha

### ISSUE THREAD

**Issue by meenapriyadarsnee** [shiksha-platform/frontend-modulefederation#213]
### Description

From Demo

**Comment by sagarkoshti1990** [comment]
this is also dependant on API @RinkleDang

**Comment by sagarihanda** [comment]
@RinkleDang - this was closed as well, right? We did not see it in demo because answers were not entered in DIKSHA, correct?

**Comment by meenapriyadarsnee** [comment]
@RinkleDang please check

**Comment by RinkleDang** [comment]
@sagarihanda yes, you are right. However, was waiting on @meenapriyadarsnee to test this but it would be difficult to since Diksha doesn't have it appropriately. It is done from our side though so closing it.
