### ISSUE TITLE
Repo name change

### ISSUE THREAD

**Issue by ChakshuGautam** [shiksha-platform/frontend-modulefederation#60]
### Description

Assuming that the _frontend_ is always going to use _modulefederation_, I think it would be a good exercise to remove that from the title of the repo.

**Comment by Shruti3004** [comment]
Hey @ChakshuGautam since we were migrating the code from the frontend repo to module federation hence we keep it like that, once it's done we'll change it's name.

**Comment by ChakshuGautam** [comment]
Aah! Thanks for the info. Closing this issue then.
